SELECT A.TARJETA, A.CODIGO_AUTORIZACION, A.MONTO, B.MONTO, B.FECHA_RECEPCION_BANCO, B.TIPO_TRX
FROM
(SELECT TARJETA, LEFT(TARJETA,6) AS TARJETA6, RIGHT(TARJETA,4) AS TARJETA4, CODIGO_AUTORIZACION, MONTO, FECHA_RECEPCION
FROM BANSUR) AS A
INNER JOIN
(SELECT INICIO6_TARJETA, FINAL4_TARJETA, TIPO_TRX,
CASE WHEN TIPO_TRX = 'CANCELADA' THEN SUM(MONTO * -1) ELSE MONTO END AS MONTO,CODIGO_AUTORIZACION,FECHA_RECEPCION_BANCO
FROM CLAP
GROUP BY INICIO6_TARJETA, FINAL4_TARJETA, TIPO_TRX, MONTO, CODIGO_AUTORIZACION, FECHA_RECEPCION_BANCO) AS B
ON A.TARJETA6 = B.INICIO6_TARJETA AND A.TARJETA4 = FINAL4_TARJETA AND A.CODIGO_AUTORIZACION = B.CODIGO_AUTORIZACION
ORDER BY A.TARJETA ASC